Adding method to change pattern expression in Bnf
PANTHEONtech/YANGinator pull request #117
Opened 2022-06-23 17:04 UTC by SaintComorek

Signed-off-by: pavol.comorek <pavol.comorek@pantheon.tech>

2022-06-24 06:49 UTC, michal-cmarada requested changes

2022-06-24 06:49 UTC, michal-cmarada commented on intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/psi/YangAbsolutePath.java
> -    @NotNull
wrong formatting, it should have 4 spaces like before, please fix formatting in all affected generated files.

2022-06-24 06:49 UTC, michal-cmarada commented on intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/YangGrammar.bnf
> +pattern-body ::= ( quoted-string | string )  optsep
this violates RFC, pattern cannot have unquoted string, please fix.

2022-06-24 06:55 UTC, JanPurdek commented on intelij-plugin/src/main/gen/tech/pantheon/yanginator/plugin/lexer/_YangLexer.flex
> +
please delete lexer before regenerating files to avoid duplicates

2022-06-28 13:51 UTC, michal-cmarada approved these changes

2022-06-28 13:51 UTC, merged